import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AuthProvider from "contexts/auth.context";

export const metadata = {
  title: "ระบบบันทึกการเยี่ยมบ้านโรงเรียนบางแพปฐมพิทยา",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Navbar />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
